# Data Collection

## Load the Libs

In [1]:
# import Lib
import pandas as pd
import datetime as dt
import pytz
import os
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf

# import module
from datetime import datetime, timezone
from datetime import date, time
from math import trunc
from dateutil.parser import parse

## Collecting Options Data from Yahoo Finance using "yfinance"

### Getting AAPL underlying stock prices

In [3]:
import yfinance as yf

# Define the ticker symbol
mb_tickerSymbol = 'AAPL'

# Get data on this ticker
mb_tickerData = yf.Ticker(mb_tickerSymbol)

# Get the historical prices for this ticker
mb_tickerDf05192023 = mb_tickerData.history(period='5y')

# See your data
print(mb_tickerDf05192023)

                                 Open        High         Low       Close  \
Date
2018-05-21 00:00:00-04:00   44.916741   45.220169   44.656321   44.828342
2018-05-22 00:00:00-04:00   45.007523   45.126982   44.625251   44.716042
2018-05-23 00:00:00-04:00   44.522525   45.036199   44.381560   45.002750
2018-05-24 00:00:00-04:00   45.100712   45.117434   44.489080   44.952579
2018-05-25 00:00:00-04:00   44.971698   45.310962   44.833124   45.055321
...                               ...         ...         ...         ...
2023-05-15 00:00:00-04:00  173.160004  173.210007  171.470001  172.070007
2023-05-16 00:00:00-04:00  171.990005  173.139999  171.800003  172.070007
2023-05-17 00:00:00-04:00  171.710007  172.929993  170.419998  172.690002
2023-05-18 00:00:00-04:00  173.000000  175.240005  172.580002  175.050003
2023-05-19 00:00:00-04:00  176.389999  176.389999  174.940002  175.160004

                             Volume  Dividends  Stock Splits
Date
2018-05-21 00:00:00-04:00  73603200        0.0           0.0
2018-05-22 00:00:00-04:00  60962800        0.0           0.0
2018-05-23 00:00:00-04:00  80233600        0.0           0.0
2018-05-24 00:00:00-04:00  92936000        0.0           0.0
2018-05-25 00:00:00-04:00  69844000        0.0           0.0
...                             ...        ...           ...
2023-05-15 00:00:00-04:00  37266700        0.0           0.0
2023-05-16 00:00:00-04:00  42110300        0.0           0.0
2023-05-17 00:00:00-04:00  57951600        0.0           0.0
2023-05-18 00:00:00-04:00  65496700        0.0           0.0
2023-05-19 00:00:00-04:00  55772400        0.0           0.0

[1259 rows x 7 columns]

In [5]:
# import Lib
import pandas as pd
import datetime as dt
import pytz
import os
import numpy as np
import matplotlib.pyplot as plt

# import module
from datetime import datetime, timezone
from datetime import date, time
from math import trunc

# get current date and time
current_datetime = datetime.now()
print("Current date & time : ", current_datetime)
filename1 = datetime.now().strftime("%Y-%m-%d %H-%M-%S-%f")

# create a file object along with extension
file_name = "mb_tickerDf05192023 "+filename1+".csv"
#print (file_name)

# converting to csv
mb_tickerDf05192023.to_csv(file_name)
print("~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~")
print("File saved named:")
print (file_name)
print(current_datetime)    
print("~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~")

Current date & time :  2023-05-21 11:06:44.380372
~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~
File saved named:
mb_tickerDf05192023 2023-05-21 11-06-44-380372.csv
2023-05-21 11:06:44.380372
~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~

### Getting AAPL stock Options related data including Implied Volatilities

In [6]:
import yfinance as yf
from datetime import datetime
import pandas as pd

# Define the ticker symbol
mb_tickerSymbol = 'AAPL'

# Get data on this ticker
mb_tickerData = yf.Ticker(mb_tickerSymbol)

# Get the option expirations
mb_options_expirations = mb_tickerData.options

# Prepare a list to hold all options data
mb_options_list = []

# Loop through each options expiration date
for expiration in mb_options_expirations:
    # Get options data for each expiration date
    mb_options_data = mb_tickerData.option_chain(expiration)
    
    # Add option type and expiration date to the data
    mb_options_data.calls['OptionType'] = 'Call'
    mb_options_data.calls['expirationDate'] = expiration
    mb_options_data.puts['OptionType'] = 'Put'
    mb_options_data.puts['expirationDate'] = expiration
    
    # Append the data to the options_list
    mb_options_list.append(mb_options_data.calls)
    mb_options_list.append(mb_options_data.puts)

# Concatenate all options data into a single DataFrame
mb_all_options_data05192023 = pd.concat(mb_options_list)

# Reset the index and drop the old one
mb_all_options_data05192023.reset_index(drop=True, inplace=True)

# Convert the expirationDate column to datetime
mb_all_options_data05192023['expirationDate'] = pd.to_datetime(mb_all_options_data05192023['expirationDate'])

# Calculate the time to expiration in days
mb_all_options_data05192023['time_to_expiration'] = (mb_all_options_data05192023['expirationDate'] - datetime.now()).dt.days

# Display the DataFrame
print(mb_all_options_data05192023)

           contractSymbol             lastTradeDate  strike  lastPrice  \
0     AAPL230526C00095000 2023-05-19 19:36:18+00:00    95.0      80.27
1     AAPL230526C00100000 2023-05-17 13:59:34+00:00   100.0      75.32
2     AAPL230526C00110000 2023-05-16 18:17:19+00:00   110.0      62.18
3     AAPL230526C00115000 2023-05-08 15:00:05+00:00   115.0      58.70
4     AAPL230526C00120000 2023-05-17 19:25:47+00:00   120.0      52.52
...                   ...                       ...     ...        ...
1628  AAPL251219P00260000 2023-05-15 18:24:01+00:00   260.0      86.91
1629  AAPL251219P00270000 2023-05-05 14:01:40+00:00   270.0      96.76
1630  AAPL251219P00290000 2023-05-11 17:03:36+00:00   290.0     116.36
1631  AAPL251219P00300000 2023-04-19 13:31:50+00:00   300.0     134.00
1632  AAPL251219P00310000 2023-05-15 18:24:01+00:00   310.0     139.21

         bid     ask    change  percentChange  volume  openInterest  \
0      78.95   81.45  1.269997       1.607591     7.0             0
1      73.50   76.50  4.639999       6.564798     1.0             6
2      63.50   66.55  0.000000       0.000000    13.0            13
3      59.10   61.55  0.000000       0.000000     1.0             3
4      53.60   56.95  0.000000       0.000000     6.0             5
...      ...     ...       ...            ...     ...           ...
1628   82.75   86.65  0.000000       0.000000    86.0             0
1629   92.75   96.65  0.000000       0.000000     1.0             0
1630  112.70  116.60  0.000000       0.000000    20.0             0
1631    0.00    0.00  0.000000       0.000000     1.0             0
1632  132.70  136.60  0.000000       0.000000    93.0             0

      impliedVolatility  inTheMoney contractSize currency OptionType  \
0              1.812501        True      REGULAR      USD       Call
1              2.871097        True      REGULAR      USD       Call
2              2.478519        True      REGULAR      USD       Call
3              1.539065        True      REGULAR      USD       Call
4              1.332035        True      REGULAR      USD       Call
...                 ...         ...          ...      ...        ...
1628           0.168923        True      REGULAR      USD        Put
1629           0.180520        True      REGULAR      USD        Put
1630           0.200753        True      REGULAR      USD        Put
1631           0.000010        True      REGULAR      USD        Put
1632           0.220070        True      REGULAR      USD        Put

     expirationDate  time_to_expiration
0        2023-05-26                   4
1        2023-05-26                   4
2        2023-05-26                   4
3        2023-05-26                   4
4        2023-05-26                   4
...             ...                 ...
1628     2025-12-19                 942
1629     2025-12-19                 942
1630     2025-12-19                 942
1631     2025-12-19                 942
1632     2025-12-19                 942

[1633 rows x 17 columns]

In [7]:
# import Lib
import pandas as pd
import datetime as dt
import pytz
import os
import numpy as np
import matplotlib.pyplot as plt

# import module
from datetime import datetime, timezone
from datetime import date, time
from math import trunc

# get current date and time
current_datetime = datetime.now()
print("Current date & time : ", current_datetime)
filename1 = datetime.now().strftime("%Y-%m-%d %H-%M-%S-%f")

# create a file object along with extension
file_name = "mb_all_options_data05192023 "+filename1+".csv"
#print (file_name)

# converting to csv
mb_all_options_data05192023.to_csv(file_name)
print("~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~")
print("File saved named:")
print (file_name)
print(current_datetime)    
print("~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~")

Current date & time :  2023-05-21 11:06:51.071892
~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~
File saved named:
mb_all_options_data05192023 2023-05-21 11-06-51-071892.csv
2023-05-21 11:06:51.071892
~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~

### Getting Interest Rate Data

In [8]:
import pandas as pd
mb_US_T_05192023 = pd.read_csv("US_Treasury_05192023.csv")
mb_US_T_05192023

   US_Treasury_Rates  Yield
0                 1m   5.62
1                 2m   5.27
2                 3m   5.29
3                 4m   5.46
4                 6m   5.36
5                 1y   5.02
6                 2y   4.28
7                 3y   3.98
8                 5y   3.76
9                 7y   3.74
10               10y   3.70
11               20y   4.07
12               30y   3.95

In [9]:
# import Lib
import pandas as pd
import datetime as dt
import pytz
import os
import numpy as np
import matplotlib.pyplot as plt

# import module
from datetime import datetime, timezone
from datetime import date, time
from math import trunc

# get current date and time
current_datetime = datetime.now()
print("Current date & time : ", current_datetime)
filename1 = datetime.now().strftime("%Y-%m-%d %H-%M-%S-%f")

# create a file object along with extension
file_name = "mb_US_T_05192023 "+filename1+".csv"
#print (file_name)

# converting to csv
mb_US_T_05192023.to_csv(file_name)
print("~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~")
print("File saved named:")
print (file_name)
print(current_datetime)    
print("~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~")

Current date & time :  2023-05-21 11:06:56.696354
~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~
File saved named:
mb_US_T_05192023 2023-05-21 11-06-56-696354.csv
2023-05-21 11:06:56.696354
~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~ ~~~~

### LOAD THE 3 CSVs

In [2]:
mb_src_prices = pd.read_csv("mb_tickerDf05192023 2023-05-21 11-06-44-380372.csv", index_col=0)
mb_src_options = pd.read_csv("mb_all_options_data05192023 2023-05-21 11-06-51-071892.csv", index_col=0)
mb_src_ir = pd.read_csv("mb_US_T_05192023 2023-05-21 11-06-56-696354.csv", index_col=0)

# Parsing the dates in the index and convert them to date only (without time or timezone info)
mb_src_prices.index = mb_src_prices.index.map(lambda x: parse(x).date())

print(mb_src_prices)
print(mb_src_options)
print(mb_src_ir)

                  Open        High         Low       Close    Volume  \
Date
2018-05-21   44.916741   45.220169   44.656321   44.828342  73603200
2018-05-22   45.007523   45.126982   44.625251   44.716042  60962800
2018-05-23   44.522525   45.036199   44.381560   45.002750  80233600
2018-05-24   45.100712   45.117434   44.489080   44.952579  92936000
2018-05-25   44.971698   45.310962   44.833124   45.055321  69844000
...                ...         ...         ...         ...       ...
2023-05-15  173.160004  173.210007  171.470001  172.070007  37266700
2023-05-16  171.990005  173.139999  171.800003  172.070007  42110300
2023-05-17  171.710007  172.929993  170.419998  172.690002  57951600
2023-05-18  173.000000  175.240005  172.580002  175.050003  65496700
2023-05-19  176.389999  176.389999  174.940002  175.160004  55772400

            Dividends  Stock Splits
Date
2018-05-21        0.0           0.0
2018-05-22        0.0           0.0
2018-05-23        0.0           0.0
2018-05-24        0.0           0.0
2018-05-25        0.0           0.0
...               ...           ...
2023-05-15        0.0           0.0
2023-05-16        0.0           0.0
2023-05-17        0.0           0.0
2023-05-18        0.0           0.0
2023-05-19        0.0           0.0

[1259 rows x 7 columns]
           contractSymbol              lastTradeDate  strike  lastPrice  \
0     AAPL230526C00095000  2023-05-19 19:36:18+00:00    95.0      80.27
1     AAPL230526C00100000  2023-05-17 13:59:34+00:00   100.0      75.32
2     AAPL230526C00110000  2023-05-16 18:17:19+00:00   110.0      62.18
3     AAPL230526C00115000  2023-05-08 15:00:05+00:00   115.0      58.70
4     AAPL230526C00120000  2023-05-17 19:25:47+00:00   120.0      52.52
...                   ...                        ...     ...        ...
1628  AAPL251219P00260000  2023-05-15 18:24:01+00:00   260.0      86.91
1629  AAPL251219P00270000  2023-05-05 14:01:40+00:00   270.0      96.76
1630  AAPL251219P00290000  2023-05-11 17:03:36+00:00   290.0     116.36
1631  AAPL251219P00300000  2023-04-19 13:31:50+00:00   300.0     134.00
1632  AAPL251219P00310000  2023-05-15 18:24:01+00:00   310.0     139.21

         bid     ask    change  percentChange  volume  openInterest  \
0      78.95   81.45  1.269997       1.607591     7.0             0
1      73.50   76.50  4.639999       6.564798     1.0             6
2      63.50   66.55  0.000000       0.000000    13.0            13
3      59.10   61.55  0.000000       0.000000     1.0             3
4      53.60   56.95  0.000000       0.000000     6.0             5
...      ...     ...       ...            ...     ...           ...
1628   82.75   86.65  0.000000       0.000000    86.0             0
1629   92.75   96.65  0.000000       0.000000     1.0             0
1630  112.70  116.60  0.000000       0.000000    20.0             0
1631    0.00    0.00  0.000000       0.000000     1.0             0
1632  132.70  136.60  0.000000       0.000000    93.0             0

      impliedVolatility  inTheMoney contractSize currency OptionType  \
0              1.812501        True      REGULAR      USD       Call
1              2.871097        True      REGULAR      USD       Call
2              2.478519        True      REGULAR      USD       Call
3              1.539065        True      REGULAR      USD       Call
4              1.332035        True      REGULAR      USD       Call
...                 ...         ...          ...      ...        ...
1628           0.168923        True      REGULAR      USD        Put
1629           0.180520        True      REGULAR      USD        Put
1630           0.200753        True      REGULAR      USD        Put
1631           0.000010        True      REGULAR      USD        Put
1632           0.220070        True      REGULAR      USD        Put

     expirationDate  time_to_expiration
0        2023-05-26                   4
1        2023-05-26                   4
2        2023-05-26                   4
3        2023-05-26                   4
4        2023-05-26                   4
...             ...                 ...
1628     2025-12-19                 942
1629     2025-12-19                 942
1630     2025-12-19                 942
1631     2025-12-19                 942
1632     2025-12-19                 942

[1633 rows x 17 columns]
   US_Treasury_Rates  Yield
0                 1m   5.62
1                 2m   5.27
2                 3m   5.29
3                 4m   5.46
4                 6m   5.36
5                 1y   5.02
6                 2y   4.28
7                 3y   3.98
8                 5y   3.76
9                 7y   3.74
10               10y   3.70
11               20y   4.07
12               30y   3.95

### Prices

In [5]:
# Copy Sources Data DataFrame
mb_prices = mb_src_prices.copy()

# Drop the unwanted columns from the DataFrame
mb_prices = mb_prices.drop(['Open', 'High', 'Low', 'Volume', 'Dividends', 'Stock Splits'], axis=1)

# Format the index to display only the date in 'yyyy-mm-dd' format
mb_prices.index = pd.to_datetime(mb_prices.index).strftime('%Y-%m-%d')

# Rename the 'Close' column to 'AAPL'
mb_prices = mb_prices.rename(columns={'Close': 'AAPL'})

# Print the updated DataFrame with formatted index
print(mb_prices)

                  AAPL
Date
2018-05-21   44.828342
2018-05-22   44.716042
2018-05-23   45.002750
2018-05-24   44.952579
2018-05-25   45.055321
...                ...
2023-05-15  172.070007
2023-05-16  172.070007
2023-05-17  172.690002
2023-05-18  175.050003
2023-05-19  175.160004

[1259 rows x 1 columns]

#### mb_prices enriched

In [6]:
import numpy as np

# Calculating the log returns
mb_prices['Log Returns'] = np.log(mb_prices['AAPL'] / mb_prices['AAPL'].shift(1))

# Number of trading days in a year
trading_days = 252

# Calculating the 1-year rolling volatility
mb_prices['1y Historical Volatility'] = mb_prices['Log Returns'].rolling(window=trading_days).std() * np.sqrt(trading_days)

# Drop the 'Log Returns' column as we don't need it anymore
mb_prices = mb_prices.drop(columns=['Log Returns'])

print(mb_prices)

                  AAPL  1y Historical Volatility
Date
2018-05-21   44.828342                       NaN
2018-05-22   44.716042                       NaN
2018-05-23   45.002750                       NaN
2018-05-24   44.952579                       NaN
2018-05-25   45.055321                       NaN
...                ...                       ...
2023-05-15  172.070007                  0.325388
2023-05-16  172.070007                  0.323930
2023-05-17  172.690002                  0.323742
2023-05-18  175.050003                  0.323074
2023-05-19  175.160004                  0.317648

[1259 rows x 2 columns]

### Options

In [73]:
# Copy Sources Data DataFrame
mb_options = mb_src_options.copy()

# Drop the unwanted columns from the DataFrame
mb_options = mb_options.drop(['bid', 'ask', 'change', 'percentChange', 'volume', 'openInterest', 'contractSize'], axis=1)

# Print the updated DataFrame with formatted index
mb_options

,contractSymbol,lastTradeDate,strike,lastPrice,impliedVolatility,inTheMoney,currency,OptionType,expirationDate,time_to_expiration
0,AAPL230526C00095000,2023-05-19 19:36:18+00:00,95.0,80.27,1.812501,True,USD,Call,2023-05-26,4
1,AAPL230526C00100000,2023-05-17 13:59:34+00:00,100.0,75.32,2.871097,True,USD,Call,2023-05-26,4
2,AAPL230526C00110000,2023-05-16 18:17:19+00:00,110.0,62.18,2.478519,True,USD,Call,2023-05-26,4
3,AAPL230526C00115000,2023-05-08 15:00:05+00:00,115.0,58.70,1.539065,True,USD,Call,2023-05-26,4
4,AAPL230526C00120000,2023-05-17 19:25:47+00:00,120.0,52.52,1.332035,True,USD,Call,2023-05-26,4
...,...,...,...,...,...,...,...,...,...,...
1628,AAPL251219P00260000,2023-05-15 18:24:01+00:00,260.0,86.91,0.168923,True,USD,Put,2025-12-19,942
1629,AAPL251219P00270000,2023-05-05 14:01:40+00:00,270.0,96.76,0.180520,True,USD,Put,2025-12-19,942
1630,AAPL251219P00290000,2023-05-11 17:03:36+00:00,290.0,116.36,0.200753,True,USD,Put,2025-12-19,942
1631,AAPL251219P00300000,2023-04-19 13:31:50+00:00,300.0,134.00,0.000010,True,USD,Put,2025-12-19,942
1632,AAPL251219P00310000,2023-05-15 18:24:01+00:00,310.0,139.21,0.220070,True,USD,Put,2025-12-19,942

### Implied Volatilities

In [24]:
# Take a Copy of the Options DataFrame
df = mb_options.copy()

# Filter for call options and create a pivot table
call_options = df[df['OptionType'] == 'Call']
call_iv_matrix = call_options.pivot(index='time_to_expiration', columns='strike', values='impliedVolatility')

# Filter for put options and create a pivot table
put_options = df[df['OptionType'] == 'Put']
put_iv_matrix = put_options.pivot(index='time_to_expiration', columns='strike', values='impliedVolatility')

# Fill NaN values with zero (optional)
call_iv_matrix = call_iv_matrix.fillna(0)
put_iv_matrix = put_iv_matrix.fillna(0)

# Sort the index and columns (optional)
call_iv_matrix.sort_index(axis=0, inplace=True)
call_iv_matrix.sort_index(axis=1, inplace=True)

put_iv_matrix.sort_index(axis=0, inplace=True)
put_iv_matrix.sort_index(axis=1, inplace=True)

In [25]:
print("Call implied volatility matrix:")
call_iv_matrix

Call implied volatility matrix:

strike,50.0,55.0,60.0,65.0,70.0,75.0,80.0,85.0,90.0,95.0,...,270.0,275.0,280.0,285.0,290.0,295.0,300.0,305.0,310.0,320.0
time_to_expiration,,,,,,,,,,,,,,,,,,,,,
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.812501,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.765626,1.734376,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25,0.000000,0.000000,1.884766,1.640627,1.648439,1.517581,1.426761,1.126957,1.231449,1.208988,...,0.744143,0.000000,0.881837,0.000000,0.562504,0.000000,0.593754,0.000000,0.000000,0.000000
32,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
39,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
60,1.410159,0.000010,1.326175,1.328128,1.215336,1.159184,0.960450,0.987305,0.912110,0.883302,...,0.250007,0.000000,0.394537,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
88,1.323246,0.000010,1.229008,0.000010,1.043950,0.983399,0.934815,0.883302,0.833254,0.784914,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
116,0.000000,0.000000,0.000000,0.951417,0.935548,0.871827,0.835451,0.805178,0.758791,0.713870,...,0.284187,0.000000,0.285163,0.000000,0.382819,0.000000,0.333991,0.000000,0.000000,0.000000
151,0.000000,1.013677,0.000010,0.000010,0.876222,0.832521,0.000010,0.749392,0.714236,0.679447,...,0.297859,0.251961,0.292488,0.277351,0.285163,0.293952,0.000000,0.000000,0.000000,0.000000
179,1.018071,0.000010,0.000000,0.000000,0.000000,0.794558,0.755374,0.719485,0.686160,0.651371,...,0.235359,0.238289,0.246101,0.125009,0.261726,0.000000,0.269539,0.000000,0.000000,0.000000
207,0.000000,0.000000,0.000000,0.827883,0.790041,0.755618,0.719729,0.686527,0.655643,0.626469,...,0.226570,0.231453,0.234383,0.236336,0.244148,0.251961,0.000000,0.000000,0.000000,0.000000
242,0.925294,0.881105,0.841554,0.801149,0.760378,0.729251,0.696780,0.666507,0.636478,0.608158,...,0.216316,0.213875,0.216805,0.228523,0.225594,0.000000,0.239265,0.000000,0.251961,0.256843
298,0.843752,0.625980,0.770754,0.741214,0.710086,0.682742,0.655521,0.623051,0.596562,0.576847,...,0.241585,0.241951,0.244148,0.254158,0.263923,0.000000,0.278328,0.000000,0.291023,0.000000
396,0.767336,0.737918,0.708743,0.683353,0.657901,0.632572,0.608524,0.586674,0.564702,0.544255,...,0.237556,0.240486,0.225472,0.228035,0.289192,0.000000,0.237312,0.000000,0.250252,0.234383
487,0.714725,0.000000,0.000000,0.642460,0.619144,0.000000,0.577763,0.000010,0.539861,0.522649,...,0.231880,0.000000,0.263496,0.000000,0.274055,0.000000,0.230232,0.000000,0.242195,0.000000
578,0.675662,0.000010,0.000010,0.000000,0.000000,0.574650,0.326911,0.000000,0.522832,0.507451,...,0.250801,0.259895,0.261177,0.262153,0.263862,0.267097,0.273994,0.275825,0.278205,0.000000
606,0.669803,0.648441,0.626591,0.602421,0.588688,0.570134,0.545659,0.535252,0.520055,0.504277,...,0.244057,0.241463,0.241646,0.243965,0.240364,0.000000,0.234139,0.000000,0.240608,0.000000
760,0.616703,0.598637,0.581059,0.564763,0.549565,0.535222,0.520207,0.505986,0.535680,0.520635,...,0.258400,0.000000,0.257820,0.000000,0.268745,0.000000,0.257271,0.000000,0.266670,0.000000
942,0.574345,0.560551,0.545537,0.531499,0.518193,0.506169,0.538304,0.523168,0.508886,0.495305,...,0.282875,0.000000,0.278114,0.000000,0.267830,0.000000,0.261177,0.000000,0.254677,0.000000

In [10]:
print("\nPut implied volatility matrix:")
put_iv_matrix

Put implied volatility matrix:

strike,50.0,55.0,60.0,65.0,70.0,75.0,80.0,85.0,90.0,95.0,...,260.0,265.0,270.0,275.0,280.0,285.0,290.0,300.0,310.0,320.0
time_to_expiration,,,,,,,,,,,,,,,,,,,,,
4,3.000002,0.000000,0.000000,0.000000,2.187505,0.000000,0.000000,0.000000,1.625002,1.500002,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,2.617191,0.000000,0.000000,0.000000,1.500002,0.000000,0.000000,0.000000,1.273441,1.332035,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.164067,1.136723,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25,0.000000,0.000000,1.218754,1.125004,1.031255,1.109379,0.953125,1.080083,1.000005,0.703128,...,2.614872,0.000000,3.050478,0.000000,2.795169,0.000000,3.623658,2.371342,0.000000,0.000000
32,1.843751,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
39,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.818361,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
60,1.199223,0.859376,0.929688,0.957032,0.726565,0.837892,0.679691,0.617191,0.570317,0.546880,...,0.636967,0.000000,1.404605,0.000000,2.032964,0.000000,0.000000,0.000000,0.000000,0.000000
88,0.781252,0.718753,0.726565,0.810549,0.753909,0.609379,0.574223,0.531255,0.500005,0.513677,...,1.237431,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
116,0.000000,0.000000,0.000000,0.617191,0.582035,0.539067,0.539067,0.519536,0.502935,0.479497,...,1.221989,0.000000,1.107365,0.000000,1.500979,0.000000,1.540926,0.598149,0.000000,0.000000
151,0.000000,0.617191,0.582035,0.531255,0.548833,0.522466,0.507817,0.486333,0.469732,0.449713,...,0.000000,0.000000,0.000000,1.396121,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
179,0.652347,0.595707,0.566411,0.513677,0.503911,0.507817,0.497564,0.475103,0.456548,0.437994,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
207,0.000000,0.000000,0.000000,0.525395,0.508794,0.494146,0.476079,0.458013,0.443853,0.426275,...,0.000000,0.000000,0.383551,0.000000,0.406744,1.057530,1.071507,0.000000,0.000000,0.000000
242,0.580082,0.555669,0.536137,0.508794,0.496099,0.479497,0.458502,0.442388,0.425543,0.409674,...,0.332404,0.532018,0.882112,0.867158,0.702273,0.977905,0.650516,0.416388,0.437384,0.455084
298,0.568364,0.564457,0.522466,0.506841,0.524907,0.499028,0.477544,0.457647,0.439825,0.422491,...,0.000000,0.000000,0.854829,0.997162,0.339789,0.749331,0.000000,0.000000,0.000000,0.000000
396,0.563481,0.596195,0.502935,0.460455,0.455572,0.430914,0.497197,0.399176,0.386481,0.432257,...,0.745913,0.269661,0.280098,0.000000,0.788119,0.000000,0.736056,0.491399,0.931672,0.411322
487,0.515142,0.537846,0.516362,0.520757,0.425665,0.402594,0.396002,0.382575,0.424933,0.407416,...,0.000000,0.000000,0.000000,0.000000,0.302192,0.000000,0.000000,0.612583,0.000000,0.000000
578,0.536626,0.505376,0.542729,0.512700,0.488653,0.466558,0.442571,0.423834,0.406744,0.392523,...,0.000000,0.373419,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
606,0.511968,0.563725,0.466924,0.474981,0.449346,0.421515,0.396368,0.378668,0.370001,0.355841,...,0.248176,0.682224,0.611363,0.276435,0.540166,0.808992,0.252327,0.450628,0.762331,0.000000
760,0.500127,0.522832,0.440801,0.458135,0.444952,0.386725,0.406012,0.393195,0.340094,0.346900,...,0.187752,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.560780,0.245918,0.000000
942,0.426886,0.477422,0.453497,0.374884,0.414068,0.395148,0.382880,0.367804,0.331306,0.326942,...,0.168923,0.000000,0.180520,0.000000,0.000000,0.000000,0.200753,0.000010,0.220070,0.000000

In [11]:
# Select first 5 and last 5 columns of Call implied volatility matrix
call_selected = pd.concat([call_iv_matrix.iloc[:, :5], call_iv_matrix.iloc[:, -5:]], axis=1)
print("Selected columns from Call implied volatility matrix:")
call_selected

Selected columns from Call implied volatility matrix:

strike,50.0,55.0,60.0,65.0,70.0,295.0,300.0,305.0,310.0,320.0
time_to_expiration,,,,,,,,,,
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25,0.000000,0.000000,1.884766,1.640627,1.648439,0.000000,0.593754,0.000000,0.000000,0.000000
32,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
39,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
60,1.410159,0.000010,1.326175,1.328128,1.215336,0.000000,0.000000,0.000000,0.000000,0.000000
88,1.323246,0.000010,1.229008,0.000010,1.043950,0.000000,0.000000,0.000000,0.000000,0.000000
116,0.000000,0.000000,0.000000,0.951417,0.935548,0.000000,0.333991,0.000000,0.000000,0.000000
151,0.000000,1.013677,0.000010,0.000010,0.876222,0.293952,0.000000,0.000000,0.000000,0.000000
179,1.018071,0.000010,0.000000,0.000000,0.000000,0.000000,0.269539,0.000000,0.000000,0.000000
207,0.000000,0.000000,0.000000,0.827883,0.790041,0.251961,0.000000,0.000000,0.000000,0.000000
242,0.925294,0.881105,0.841554,0.801149,0.760378,0.000000,0.239265,0.000000,0.251961,0.256843
298,0.843752,0.625980,0.770754,0.741214,0.710086,0.000000,0.278328,0.000000,0.291023,0.000000
396,0.767336,0.737918,0.708743,0.683353,0.657901,0.000000,0.237312,0.000000,0.250252,0.234383
487,0.714725,0.000000,0.000000,0.642460,0.619144,0.000000,0.230232,0.000000,0.242195,0.000000
578,0.675662,0.000010,0.000010,0.000000,0.000000,0.267097,0.273994,0.275825,0.278205,0.000000
606,0.669803,0.648441,0.626591,0.602421,0.588688,0.000000,0.234139,0.000000,0.240608,0.000000
760,0.616703,0.598637,0.581059,0.564763,0.549565,0.000000,0.257271,0.000000,0.266670,0.000000
942,0.574345,0.560551,0.545537,0.531499,0.518193,0.000000,0.261177,0.000000,0.254677,0.000000

In [12]:
# Select first 5 and last 5 columns of Put implied volatility matrix
put_selected = pd.concat([put_iv_matrix.iloc[:, :5], put_iv_matrix.iloc[:, -5:]], axis=1)
print("\nSelected columns from Put implied volatility matrix:")
put_selected

Selected columns from Put implied volatility matrix:

strike,50.0,55.0,60.0,65.0,70.0,285.0,290.0,300.0,310.0,320.0
time_to_expiration,,,,,,,,,,
4,3.000002,0.000000,0.000000,0.000000,2.187505,0.000000,0.000000,0.000000,0.000000,0.000000
11,2.617191,0.000000,0.000000,0.000000,1.500002,0.000000,0.000000,0.000000,0.000000,0.000000
18,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25,0.000000,0.000000,1.218754,1.125004,1.031255,0.000000,3.623658,2.371342,0.000000,0.000000
32,1.843751,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
39,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
60,1.199223,0.859376,0.929688,0.957032,0.726565,0.000000,0.000000,0.000000,0.000000,0.000000
88,0.781252,0.718753,0.726565,0.810549,0.753909,0.000000,0.000000,0.000000,0.000000,0.000000
116,0.000000,0.000000,0.000000,0.617191,0.582035,0.000000,1.540926,0.598149,0.000000,0.000000
151,0.000000,0.617191,0.582035,0.531255,0.548833,0.000000,0.000000,0.000000,0.000000,0.000000
179,0.652347,0.595707,0.566411,0.513677,0.503911,0.000000,0.000000,0.000000,0.000000,0.000000
207,0.000000,0.000000,0.000000,0.525395,0.508794,1.057530,1.071507,0.000000,0.000000,0.000000
242,0.580082,0.555669,0.536137,0.508794,0.496099,0.977905,0.650516,0.416388,0.437384,0.455084
298,0.568364,0.564457,0.522466,0.506841,0.524907,0.749331,0.000000,0.000000,0.000000,0.000000
396,0.563481,0.596195,0.502935,0.460455,0.455572,0.000000,0.736056,0.491399,0.931672,0.411322
487,0.515142,0.537846,0.516362,0.520757,0.425665,0.000000,0.000000,0.612583,0.000000,0.000000
578,0.536626,0.505376,0.542729,0.512700,0.488653,0.000000,0.000000,0.000000,0.000000,0.000000
606,0.511968,0.563725,0.466924,0.474981,0.449346,0.808992,0.252327,0.450628,0.762331,0.000000
760,0.500127,0.522832,0.440801,0.458135,0.444952,0.000000,0.000000,0.560780,0.245918,0.000000
942,0.426886,0.477422,0.453497,0.374884,0.414068,0.000000,0.200753,0.000010,0.220070,0.000000

#### mb_iv

In [98]:
'''
Let's now combine the 2 matrices in to one mb_iv
The rule here is to take the average of the 2 when the vol is not zero or not n/a
'''

# First replace zeros with NaN in both matrices
call_iv_matrix.replace(0, np.nan, inplace=True)
put_iv_matrix.replace(0, np.nan, inplace=True)

# Define a custom function to calculate average if neither is zero or NaN
def custom_combine(ser1, ser2):
    ser1_valid = ser1.notna()
    ser2_valid = ser2.notna()
    both_valid = ser1_valid & ser2_valid
    return pd.Series(np.where(both_valid, (ser1 + ser2)/2, np.where(ser1_valid, ser1, ser2)), index=ser1.index)

# Apply the custom function column-wise
mb_iv = call_iv_matrix.combine(put_iv_matrix, custom_combine)

print("Combined implied volatility matrix:")
print(mb_iv)

Combined implied volatility matrix:
strike                 50.0      55.0      60.0      65.0      70.0   \
time_to_expiration
4                   3.000002       NaN       NaN       NaN  2.187505
11                  2.617191       NaN       NaN       NaN  1.500002
18                       NaN       NaN       NaN       NaN       NaN
25                       NaN       NaN  1.551760  1.382816  1.339847
32                  1.843751       NaN       NaN       NaN       NaN
39                       NaN       NaN       NaN       NaN       NaN
60                  1.304691  0.429693  1.127932  1.142580  0.970951
88                  1.052249  0.359381  0.977786  0.405279  0.898929
116                      NaN       NaN       NaN  0.784304  0.758791
151                      NaN  0.815434  0.291023  0.265632  0.712527
179                 0.835209  0.297859  0.566411  0.513677  0.503911
207                      NaN       NaN       NaN  0.676639  0.649418
242                 0.752688  0.718387  0.688846  0.654972  0.628239
298                 0.706058  0.595219  0.646610  0.624027  0.617497
396                 0.665409  0.667057  0.605839  0.571904  0.556737
487                 0.614933  0.537846  0.516362  0.581608  0.522405
578                 0.606144  0.252693  0.271370  0.512700  0.488653
606                 0.590885  0.606083  0.546757  0.538701  0.519017
760                 0.558415  0.560734  0.510930  0.511449  0.497258
942                 0.500615  0.518987  0.499517  0.453192  0.466131

strike                 75.0      80.0      85.0      90.0      95.0   ...  \
time_to_expiration                                                    ...
4                        NaN       NaN       NaN  1.625002  1.656252  ...
11                       NaN       NaN  1.765626  1.503909  1.332035  ...
18                       NaN       NaN       NaN  1.164067  1.136723  ...
25                  1.313480  1.189943  1.103520  1.115727  0.956058  ...
32                       NaN       NaN       NaN       NaN       NaN  ...
39                       NaN       NaN       NaN  0.818361       NaN  ...
60                  0.998538  0.820070  0.802248  0.741214  0.715091  ...
88                  0.796389  0.754519  0.707278  0.666629  0.649295  ...
116                 0.705447  0.687259  0.662357  0.630863  0.596684  ...
151                 0.677493  0.253914  0.617863  0.591984  0.564580  ...
179                 0.651188  0.626469  0.597294  0.571354  0.544682  ...
207                 0.624882  0.597904  0.572270  0.549748  0.526372  ...
242                 0.604374  0.577641  0.554448  0.531011  0.508916  ...
298                 0.590885  0.566533  0.540349  0.518193  0.499669  ...
396                 0.531743  0.552861  0.492925  0.475591  0.488256  ...
487                 0.402594  0.486883  0.191292  0.482397  0.465032  ...
578                 0.520604  0.384741  0.423834  0.464788  0.449987  ...
606                 0.495824  0.471014  0.456960  0.445028  0.430059  ...
760                 0.460973  0.463110  0.449590  0.437887  0.433767  ...
942                 0.450659  0.460592  0.445486  0.420096  0.411123  ...

strike                 270.0     275.0     280.0     285.0     290.0  \
time_to_expiration
4                        NaN       NaN       NaN       NaN       NaN
11                       NaN       NaN       NaN       NaN       NaN
18                       NaN       NaN       NaN       NaN       NaN
25                  1.897311       NaN  1.838503       NaN  2.093081
32                       NaN       NaN       NaN       NaN       NaN
39                       NaN       NaN       NaN       NaN       NaN
60                  0.827306       NaN  1.213751       NaN       NaN
88                       NaN       NaN       NaN       NaN       NaN
116                 0.695776       NaN  0.893071       NaN  0.961873
151                 0.297859  0.824041  0.292488  0.277351  0.285163
179                 0.235359  0.238289  0.246101  0.125009  0.261726
207                 0.305061  0.231453  0.320563  0.646933  0.657828
242                 0.549214  0.540517  0.459539  0.603214  0.438055
298                 0.548207  0.619556  0.291969  0.501744  0.263923
396                 0.258827  0.240486  0.506795  0.228035  0.512624
487                 0.231880       NaN  0.282844       NaN  0.274055
578                 0.250801  0.259895  0.261177  0.262153  0.263862
606                 0.427710  0.258949  0.390906  0.526479  0.246345
760                 0.258400       NaN  0.257820       NaN  0.268745
942                 0.231697       NaN  0.278114       NaN  0.234291

strike                 295.0     300.0     305.0     310.0     320.0
time_to_expiration
4                        NaN       NaN       NaN       NaN       NaN
11                       NaN       NaN       NaN       NaN       NaN
18                       NaN       NaN       NaN       NaN       NaN
25                       NaN  1.482548       NaN       NaN       NaN
32                       NaN       NaN       NaN       NaN       NaN
39                       NaN       NaN       NaN       NaN       NaN
60                       NaN       NaN       NaN       NaN       NaN
88                       NaN       NaN       NaN       NaN       NaN
116                      NaN  0.466070       NaN       NaN       NaN
151                 0.293952       NaN       NaN       NaN       NaN
179                      NaN  0.269539       NaN       NaN       NaN
207                 0.251961       NaN       NaN       NaN       NaN
242                      NaN  0.327827       NaN  0.344672  0.355963
298                      NaN  0.278328       NaN  0.291023       NaN
396                      NaN  0.364356       NaN  0.590962  0.322852
487                      NaN  0.421408       NaN  0.242195       NaN
578                 0.267097  0.273994  0.275825  0.278205       NaN
606                      NaN  0.342383       NaN  0.501470       NaN
760                      NaN  0.409025       NaN  0.256294       NaN
942                      NaN  0.130593       NaN  0.237373       NaN

[20 rows x 69 columns]

In [99]:
# Select first 5 and last 5 columns of implied volatility matrix
iv_selected = pd.concat([mb_iv.iloc[:, :5], mb_iv.iloc[:, -5:]], axis=1)
print("\nSelected columns from Put implied volatility matrix:")
iv_selected

Selected columns from Put implied volatility matrix:

strike,50.0,55.0,60.0,65.0,70.0,295.0,300.0,305.0,310.0,320.0
time_to_expiration,,,,,,,,,,
4,3.000002,NaN,NaN,NaN,2.187505,NaN,NaN,NaN,NaN,NaN
11,2.617191,NaN,NaN,NaN,1.500002,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,1.551760,1.382816,1.339847,NaN,1.482548,NaN,NaN,NaN
32,1.843751,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,1.304691,0.429693,1.127932,1.142580,0.970951,NaN,NaN,NaN,NaN,NaN
88,1.052249,0.359381,0.977786,0.405279,0.898929,NaN,NaN,NaN,NaN,NaN
116,NaN,NaN,NaN,0.784304,0.758791,NaN,0.466070,NaN,NaN,NaN
151,NaN,0.815434,0.291023,0.265632,0.712527,0.293952,NaN,NaN,NaN,NaN
179,0.835209,0.297859,0.566411,0.513677,0.503911,NaN,0.269539,NaN,NaN,NaN
207,NaN,NaN,NaN,0.676639,0.649418,0.251961,NaN,NaN,NaN,NaN
242,0.752688,0.718387,0.688846,0.654972,0.628239,NaN,0.327827,NaN,0.344672,0.355963
298,0.706058,0.595219,0.646610,0.624027,0.617497,NaN,0.278328,NaN,0.291023,NaN
396,0.665409,0.667057,0.605839,0.571904,0.556737,NaN,0.364356,NaN,0.590962,0.322852
487,0.614933,0.537846,0.516362,0.581608,0.522405,NaN,0.421408,NaN,0.242195,NaN
578,0.606144,0.252693,0.271370,0.512700,0.488653,0.267097,0.273994,0.275825,0.278205,NaN
606,0.590885,0.606083,0.546757,0.538701,0.519017,NaN,0.342383,NaN,0.501470,NaN
760,0.558415,0.560734,0.510930,0.511449,0.497258,NaN,0.409025,NaN,0.256294,NaN
942,0.500615,0.518987,0.499517,0.453192,0.466131,NaN,0.130593,NaN,0.237373,NaN

### Interest Rates

In [3]:
# Copy Sources Data DataFrame
mb_interest_rates = mb_src_ir.copy()

# Print the updated DataFrame with formatted index
print(mb_interest_rates)

   US_Treasury_Rates  Yield
0                 1m   5.62
1                 2m   5.27
2                 3m   5.29
3                 4m   5.46
4                 6m   5.36
5                 1y   5.02
6                 2y   4.28
7                 3y   3.98
8                 5y   3.76
9                 7y   3.74
10               10y   3.70
11               20y   4.07
12               30y   3.95

### Preparing Data for Model Development and Testing

#### Preparing the underlying price

In [21]:
price_on_date = mb_prices.loc['2023-05-19', 'AAPL']
print(f"The price of AAPL on 2023-05-19 was {price_on_date}")

The price of AAPL on 2023-05-19 was 175.16000366210938

175.16000366210938

#### Preparing the options static data

In [100]:
# First, make a copy of your DataFrame
mb_options_copy = mb_options.copy()

# Add new column 'OptionStyle' and set all its values to 'American'
mb_options_copy['OptionStyle'] = 'American'

mb_options_copy

,contractSymbol,lastTradeDate,strike,lastPrice,impliedVolatility,inTheMoney,currency,OptionType,expirationDate,time_to_expiration,OptionStyle
0,AAPL230526C00095000,2023-05-19 19:36:18+00:00,95.0,80.27,1.812501,True,USD,Call,2023-05-26,4,American
1,AAPL230526C00100000,2023-05-17 13:59:34+00:00,100.0,75.32,2.871097,True,USD,Call,2023-05-26,4,American
2,AAPL230526C00110000,2023-05-16 18:17:19+00:00,110.0,62.18,2.478519,True,USD,Call,2023-05-26,4,American
3,AAPL230526C00115000,2023-05-08 15:00:05+00:00,115.0,58.70,1.539065,True,USD,Call,2023-05-26,4,American
4,AAPL230526C00120000,2023-05-17 19:25:47+00:00,120.0,52.52,1.332035,True,USD,Call,2023-05-26,4,American
...,...,...,...,...,...,...,...,...,...,...,...
1628,AAPL251219P00260000,2023-05-15 18:24:01+00:00,260.0,86.91,0.168923,True,USD,Put,2025-12-19,942,American
1629,AAPL251219P00270000,2023-05-05 14:01:40+00:00,270.0,96.76,0.180520,True,USD,Put,2025-12-19,942,American
1630,AAPL251219P00290000,2023-05-11 17:03:36+00:00,290.0,116.36,0.200753,True,USD,Put,2025-12-19,942,American
1631,AAPL251219P00300000,2023-04-19 13:31:50+00:00,300.0,134.00,0.000010,True,USD,Put,2025-12-19,942,American
1632,AAPL251219P00310000,2023-05-15 18:24:01+00:00,310.0,139.21,0.220070,True,USD,Put,2025-12-19,942,American

In [101]:
print(mb_options_copy.columns)

Index(['contractSymbol', 'lastTradeDate', 'strike', 'lastPrice',
       'impliedVolatility', 'inTheMoney', 'currency', 'OptionType',
       'expirationDate', 'time_to_expiration', 'OptionStyle'],
      dtype='object')

In [102]:
# The columns we are interested in.
columns_to_check = ['strike', 'inTheMoney', 'currency', 'OptionType', 'time_to_expiration', 'OptionStyle']

for column in columns_to_check:
    print(f"{column}: {mb_options_copy[column].unique()}")

strike: [ 95.  100.  110.  115.  120.  125.  130.  135.  140.  145.  147.  149.
 150.  152.5 155.  157.5 160.  162.5 165.  167.5 170.  172.5 175.  177.5
 180.  182.5 185.  187.5 190.  192.5 195.  197.5 200.  202.5 205.  210.
 215.  220.  225.  230.  240.  250.   50.   70.   90.  105.  146.  148.
  85.  245.  235.   60.   65.   75.   80.  255.  260.  270.  280.  290.
 300.   55.  265.  275.  285.  295.  310.  320.  305. ]
inTheMoney: [ True False]
currency: ['USD']
OptionType: ['Call' 'Put']
time_to_expiration: [  4  11  18  25  32  39  60  88 116 151 179 207 242 298 396 487 578 606
 760 942]
OptionStyle: ['American']

In [103]:
import pandas as pd
# Display up to 500 rows and 500 columns
#pd.set_option('display.max_rows', 500)
#pd.set_option('display.max_columns', 500)

pivot_table = mb_options_copy.pivot_table(index='strike', 
                                          columns='OptionType', 
                                          values='contractSymbol', 
                                          aggfunc='count')

print(pivot_table)

OptionType  Call   Put
strike
50.0        11.0  14.0
55.0        11.0  12.0
60.0        11.0  13.0
65.0        13.0  15.0
70.0        13.0  17.0
...          ...   ...
295.0        3.0   NaN
300.0       11.0   8.0
305.0        1.0   NaN
310.0        8.0   5.0
320.0        2.0   2.0

[69 rows x 2 columns]

In [104]:
import pandas as pd
# Display up to 500 rows and 500 columns
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

pivot_table = mb_options_copy.pivot_table(index='OptionType', 
                                          columns='strike', 
                                          values='contractSymbol', 
                                          aggfunc='count')

print(pivot_table)

strike      50.0   55.0   60.0   65.0   70.0   75.0   80.0   85.0   90.0   \
OptionType
Call         11.0   11.0   11.0   13.0   13.0   14.0   15.0   15.0   16.0
Put          14.0   12.0   13.0   15.0   17.0   15.0   15.0   15.0   19.0

strike      95.0   100.0  105.0  110.0  115.0  120.0  125.0  130.0  135.0  \
OptionType
Call         16.0   18.0   15.0   20.0   17.0   17.0   18.0   20.0   20.0
Put          18.0   20.0   20.0   20.0   20.0   20.0   20.0   20.0   20.0

strike      140.0  145.0  146.0  147.0  148.0  149.0  150.0  152.5  155.0  \
OptionType
Call         20.0   20.0    NaN    1.0    NaN    1.0   20.0    2.0   20.0
Put          20.0   20.0    1.0    1.0    1.0    1.0   20.0    2.0   20.0

strike      157.5  160.0  162.5  165.0  167.5  170.0  172.5  175.0  177.5  \
OptionType
Call          2.0   20.0    2.0   20.0    2.0   20.0    2.0   20.0    2.0
Put           2.0   20.0    2.0   20.0    2.0   20.0    2.0   20.0    2.0

strike      180.0  182.5  185.0  187.5  190.0  192.5  195.0  197.5  200.0  \
OptionType
Call         20.0    2.0   20.0    2.0   20.0    2.0   20.0    2.0   20.0
Put          20.0    2.0   20.0    1.0   20.0    NaN   20.0    NaN   20.0

strike      202.5  205.0  210.0  215.0  220.0  225.0  230.0  235.0  240.0  \
OptionType
Call          2.0   20.0   19.0   17.0   19.0   18.0   18.0   15.0   17.0
Put           1.0   16.0   18.0   12.0   15.0    9.0   11.0    8.0    9.0

strike      245.0  250.0  255.0  260.0  265.0  270.0  275.0  280.0  285.0  \
OptionType
Call         16.0   17.0   11.0   14.0    9.0   14.0    8.0   14.0    8.0
Put           6.0   13.0    6.0    9.0    4.0    9.0    4.0    9.0    4.0

strike      290.0  295.0  300.0  305.0  310.0  320.0
OptionType
Call         13.0    3.0   11.0    1.0    8.0    2.0
Put           7.0    NaN    8.0    NaN    5.0    2.0

In [105]:
# To reset pandas' display options to their defaults
import pandas as pd

pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')

In [106]:
mb_options_sorted = mb_options_copy.sort_values(by='lastTradeDate')
mb_options_sorted.head(100)

,contractSymbol,lastTradeDate,strike,lastPrice,impliedVolatility,inTheMoney,currency,OptionType,expirationDate,time_to_expiration,OptionStyle
1444,AAPL250117P00270000,2022-09-21 15:51:08+00:00,270.0,113.62,0.611363,True,USD,Put,2025-01-17,606,American
621,AAPL230915P00270000,2022-09-29 18:49:54+00:00,270.0,128.77,1.107365,True,USD,Put,2023-09-15,116,American
1174,AAPL240621P00310000,2022-10-07 15:12:54+00:00,310.0,168.53,0.931672,True,USD,Put,2024-06-21,396,American
1172,AAPL240621P00290000,2022-10-13 14:30:33+00:00,290.0,154.38,0.736056,True,USD,Put,2024-06-21,396,American
971,AAPL240119P00270000,2022-10-14 16:09:47+00:00,270.0,130.59,0.882112,True,USD,Put,2024-01-19,242,American
...,...,...,...,...,...,...,...,...,...,...,...
968,AAPL240119P00255000,2023-04-13 19:33:43+00:00,255.0,89.50,0.367072,True,USD,Put,2024-01-19,242,American
464,AAPL230721P00250000,2023-04-14 16:12:55+00:00,250.0,85.39,0.688724,True,USD,Put,2023-07-21,60,American
1437,AAPL250117P00235000,2023-04-14 18:14:12+00:00,235.0,70.55,0.219765,True,USD,Put,2025-01-17,606,American
422,AAPL230721C00270000,2023-04-17 13:44:00+00:00,270.0,0.01,0.250007,False,USD,Call,2023-07-21,60,American
153,AAPL230602P00195000,2023-04-17 14:47:30+00:00,195.0,30.75,0.650394,True,USD,Put,2023-06-02,11,American

In [96]:
unique_strikes_first = mb_options_sorted['strike'].head(100).unique()
unique_strikes_first.sort()
print(unique_strikes_first)

[ 55.  60.  65.  80.  85. 105. 115. 195. 215. 220. 225. 230. 235. 240.
 245. 250. 255. 260. 265. 270. 275. 280. 285. 290. 300. 310. 320.]

In [81]:
mb_options_sorted = mb_options_copy.sort_values(by='lastTradeDate', ascending=False)
mb_options_sorted.head(100)

,contractSymbol,lastTradeDate,strike,lastPrice,impliedVolatility,inTheMoney,currency,OptionType,expirationDate,time_to_expiration,OptionStyle
22,AAPL230526C00175000,2023-05-19 19:59:59+00:00,175.0,1.77,0.197518,True,USD,Call,2023-05-26,4,American
231,AAPL230616C00175000,2023-05-19 19:59:58+00:00,175.0,4.20,0.219490,True,USD,Call,2023-06-16,25,American
104,AAPL230602C00177500,2023-05-19 19:59:58+00:00,177.5,1.44,0.193734,False,USD,Call,2023-06-02,11,American
70,AAPL230526P00175000,2023-05-19 19:59:58+00:00,175.0,1.45,0.171883,False,USD,Put,2023-05-26,4,American
69,AAPL230526P00172500,2023-05-19 19:59:57+00:00,172.5,0.66,0.187020,False,USD,Put,2023-05-26,4,American
...,...,...,...,...,...,...,...,...,...,...,...
371,AAPL230630P00165000,2023-05-19 19:58:04+00:00,165.0,1.40,0.220711,False,USD,Put,2023-06-30,39,American
353,AAPL230630C00190000,2023-05-19 19:58:04+00:00,190.0,0.40,0.174569,False,USD,Call,2023-06-30,39,American
370,AAPL230630P00160000,2023-05-19 19:58:04+00:00,160.0,0.87,0.242683,False,USD,Put,2023-06-30,39,American
445,AAPL230721P00155000,2023-05-19 19:58:04+00:00,155.0,1.02,0.253914,False,USD,Put,2023-07-21,60,American
407,AAPL230721C00185000,2023-05-19 19:57:59+00:00,185.0,1.96,0.189095,False,USD,Call,2023-07-21,60,American

#### Preparing the volatilities grid

In [107]:
mb_iv

strike,50.0,55.0,60.0,65.0,70.0,75.0,80.0,85.0,90.0,95.0,...,270.0,275.0,280.0,285.0,290.0,295.0,300.0,305.0,310.0,320.0
time_to_expiration,,,,,,,,,,,,,,,,,,,,,
4,3.000002,NaN,NaN,NaN,2.187505,NaN,NaN,NaN,1.625002,1.656252,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2.617191,NaN,NaN,NaN,1.500002,NaN,NaN,1.765626,1.503909,1.332035,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.164067,1.136723,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,1.551760,1.382816,1.339847,1.313480,1.189943,1.103520,1.115727,0.956058,...,1.897311,NaN,1.838503,NaN,2.093081,NaN,1.482548,NaN,NaN,NaN
32,1.843751,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.818361,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,1.304691,0.429693,1.127932,1.142580,0.970951,0.998538,0.820070,0.802248,0.741214,0.715091,...,0.827306,NaN,1.213751,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,1.052249,0.359381,0.977786,0.405279,0.898929,0.796389,0.754519,0.707278,0.666629,0.649295,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,NaN,NaN,NaN,0.784304,0.758791,0.705447,0.687259,0.662357,0.630863,0.596684,...,0.695776,NaN,0.893071,NaN,0.961873,NaN,0.466070,NaN,NaN,NaN
151,NaN,0.815434,0.291023,0.265632,0.712527,0.677493,0.253914,0.617863,0.591984,0.564580,...,0.297859,0.824041,0.292488,0.277351,0.285163,0.293952,NaN,NaN,NaN,NaN
179,0.835209,0.297859,0.566411,0.513677,0.503911,0.651188,0.626469,0.597294,0.571354,0.544682,...,0.235359,0.238289,0.246101,0.125009,0.261726,NaN,0.269539,NaN,NaN,NaN
207,NaN,NaN,NaN,0.676639,0.649418,0.624882,0.597904,0.572270,0.549748,0.526372,...,0.305061,0.231453,0.320563,0.646933,0.657828,0.251961,NaN,NaN,NaN,NaN
242,0.752688,0.718387,0.688846,0.654972,0.628239,0.604374,0.577641,0.554448,0.531011,0.508916,...,0.549214,0.540517,0.459539,0.603214,0.438055,NaN,0.327827,NaN,0.344672,0.355963
298,0.706058,0.595219,0.646610,0.624027,0.617497,0.590885,0.566533,0.540349,0.518193,0.499669,...,0.548207,0.619556,0.291969,0.501744,0.263923,NaN,0.278328,NaN,0.291023,NaN
396,0.665409,0.667057,0.605839,0.571904,0.556737,0.531743,0.552861,0.492925,0.475591,0.488256,...,0.258827,0.240486,0.506795,0.228035,0.512624,NaN,0.364356,NaN,0.590962,0.322852
487,0.614933,0.537846,0.516362,0.581608,0.522405,0.402594,0.486883,0.191292,0.482397,0.465032,...,0.231880,NaN,0.282844,NaN,0.274055,NaN,0.421408,NaN,0.242195,NaN
578,0.606144,0.252693,0.271370,0.512700,0.488653,0.520604,0.384741,0.423834,0.464788,0.449987,...,0.250801,0.259895,0.261177,0.262153,0.263862,0.267097,0.273994,0.275825,0.278205,NaN
606,0.590885,0.606083,0.546757,0.538701,0.519017,0.495824,0.471014,0.456960,0.445028,0.430059,...,0.427710,0.258949,0.390906,0.526479,0.246345,NaN,0.342383,NaN,0.501470,NaN
760,0.558415,0.560734,0.510930,0.511449,0.497258,0.460973,0.463110,0.449590,0.437887,0.433767,...,0.258400,NaN,0.257820,NaN,0.268745,NaN,0.409025,NaN,0.256294,NaN
942,0.500615,0.518987,0.499517,0.453192,0.466131,0.450659,0.460592,0.445486,0.420096,0.411123,...,0.231697,NaN,0.278114,NaN,0.234291,NaN,0.130593,NaN,0.237373,NaN

In [109]:
# Take a copy of mb_iv
mb_iv_std = mb_iv.copy()

# Filter rows based on time_to_expiration
desired_tenors = [4, 11, 32, 60, 88, 179, 298, 396, 578, 760, 942]
mb_iv_std = mb_iv_std[mb_iv_std.index.isin(desired_tenors)]

print(mb_iv_std)

strike                 50.0      55.0      60.0      65.0      70.0   \
time_to_expiration
4                   3.000002       NaN       NaN       NaN  2.187505
11                  2.617191       NaN       NaN       NaN  1.500002
32                  1.843751       NaN       NaN       NaN       NaN
60                  1.304691  0.429693  1.127932  1.142580  0.970951
88                  1.052249  0.359381  0.977786  0.405279  0.898929
179                 0.835209  0.297859  0.566411  0.513677  0.503911
298                 0.706058  0.595219  0.646610  0.624027  0.617497
396                 0.665409  0.667057  0.605839  0.571904  0.556737
578                 0.606144  0.252693  0.271370  0.512700  0.488653
760                 0.558415  0.560734  0.510930  0.511449  0.497258
942                 0.500615  0.518987  0.499517  0.453192  0.466131

strike                 75.0      80.0      85.0      90.0      95.0   ...  \
time_to_expiration                                                    ...
4                        NaN       NaN       NaN  1.625002  1.656252  ...
11                       NaN       NaN  1.765626  1.503909  1.332035  ...
32                       NaN       NaN       NaN       NaN       NaN  ...
60                  0.998538  0.820070  0.802248  0.741214  0.715091  ...
88                  0.796389  0.754519  0.707278  0.666629  0.649295  ...
179                 0.651188  0.626469  0.597294  0.571354  0.544682  ...
298                 0.590885  0.566533  0.540349  0.518193  0.499669  ...
396                 0.531743  0.552861  0.492925  0.475591  0.488256  ...
578                 0.520604  0.384741  0.423834  0.464788  0.449987  ...
760                 0.460973  0.463110  0.449590  0.437887  0.433767  ...
942                 0.450659  0.460592  0.445486  0.420096  0.411123  ...

strike                 270.0     275.0     280.0     285.0     290.0  \
time_to_expiration
4                        NaN       NaN       NaN       NaN       NaN
11                       NaN       NaN       NaN       NaN       NaN
32                       NaN       NaN       NaN       NaN       NaN
60                  0.827306       NaN  1.213751       NaN       NaN
88                       NaN       NaN       NaN       NaN       NaN
179                 0.235359  0.238289  0.246101  0.125009  0.261726
298                 0.548207  0.619556  0.291969  0.501744  0.263923
396                 0.258827  0.240486  0.506795  0.228035  0.512624
578                 0.250801  0.259895  0.261177  0.262153  0.263862
760                 0.258400       NaN  0.257820       NaN  0.268745
942                 0.231697       NaN  0.278114       NaN  0.234291

strike                 295.0     300.0     305.0     310.0     320.0
time_to_expiration
4                        NaN       NaN       NaN       NaN       NaN
11                       NaN       NaN       NaN       NaN       NaN
32                       NaN       NaN       NaN       NaN       NaN
60                       NaN       NaN       NaN       NaN       NaN
88                       NaN       NaN       NaN       NaN       NaN
179                      NaN  0.269539       NaN       NaN       NaN
298                      NaN  0.278328       NaN  0.291023       NaN
396                      NaN  0.364356       NaN  0.590962  0.322852
578                 0.267097  0.273994  0.275825  0.278205       NaN
760                      NaN  0.409025       NaN  0.256294       NaN
942                      NaN  0.130593       NaN  0.237373       NaN

[11 rows x 69 columns]

In [113]:
# Specify the desired strike values (19 Stike points)
desired_strikes = [120, 125, 130, 135,
                   140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190, 195, 200, 205, 210]

# Filter columns based on desired_strikes
mb_iv_std = mb_iv_std[desired_strikes]

mb_iv_std

strike,120.0,125.0,130.0,135.0,140.0,145.0,150.0,155.0,160.0,165.0,170.0,175.0,180.0,185.0,190.0,195.0,200.0,205.0,210.0
time_to_expiration,,,,,,,,,,,,,,,,,,,
4,1.150392,1.047854,0.996097,1.130618,0.741214,0.730960,0.547856,0.492681,0.417730,0.318366,0.234505,0.184701,0.173836,0.268806,0.316901,0.510503,0.555913,0.503911,0.872563
11,1.155031,0.795412,0.713382,0.644535,0.607426,0.518560,0.453130,0.398688,0.332770,0.267708,0.233772,0.185860,0.161019,0.234383,0.314704,0.448248,0.449835,0.533452,0.491216
32,0.503911,0.472662,0.543950,0.482793,0.495000,0.466314,0.418829,0.322822,0.283699,0.251533,0.234413,0.197030,0.177834,0.171761,0.245369,0.252632,0.298225,0.218758,0.240242
60,0.539800,0.489324,0.454351,0.430670,0.429571,0.359320,0.344764,0.299751,0.274971,0.248726,0.225350,0.202401,0.181405,0.160653,0.191811,0.215584,0.221382,0.241768,0.282966
88,0.484380,0.455572,0.468572,0.440008,0.386298,0.366583,0.334418,0.305854,0.286537,0.266243,0.246498,0.227181,0.208840,0.190651,0.197335,0.198677,0.194100,0.222847,0.251350
179,0.431280,0.424963,0.404974,0.390265,0.362128,0.347480,0.328910,0.310096,0.306373,0.294685,0.275550,0.253486,0.236610,0.222710,0.217964,0.209481,0.197823,0.221504,0.223244
298,0.409826,0.407263,0.384772,0.375647,0.352393,0.342994,0.325263,0.323783,0.299308,0.297508,0.277153,0.279533,0.264824,0.247505,0.229775,0.232674,0.218620,0.214745,0.203560
396,0.408117,0.389441,0.378455,0.361899,0.350272,0.337882,0.323630,0.321738,0.305488,0.299949,0.290115,0.275291,0.264923,0.251839,0.255073,0.231514,0.222954,0.210335,0.220268
578,0.381079,0.378699,0.367850,0.352958,0.345801,0.339087,0.326179,0.321952,0.316840,0.310371,0.298271,0.293479,0.284736,0.271827,0.258217,0.252006,0.243591,0.242096,0.230225
760,0.371375,0.367789,0.353392,0.347403,0.337157,0.330771,0.322929,0.315246,0.307151,0.301475,0.294067,0.290031,0.273216,0.271461,0.271362,0.264930,0.255760,0.245300,0.235222
942,0.361052,0.352958,0.346717,0.335380,0.332107,0.324149,0.316741,0.307250,0.301177,0.297325,0.288192,0.287208,0.276176,0.270828,0.266380,0.257263,0.255249,0.246010,0.242836

In [71]:
# Interpolate and then fill remaining NaNs for each row
mb_iv_std = mb_iv_std.apply(lambda row: row.interpolate(method='linear').fillna(method='bfill').fillna(method='ffill'), axis=1)
mb_iv_std

strike,100.0,105.0,110.0,115.0,120.0,125.0,130.0,135.0,140.0,145.0,...,205.0,210.0,215.0,220.0,225.0,230.0,235.0,240.0,245.0,250.0
time_to_expiration,,,,,,,,,,,,,,,,,,,,,
4,2.123050,1.250004,1.817387,1.300785,1.150392,1.047854,0.996097,1.130618,0.741214,0.730960,...,0.503911,0.872563,0.531255,0.946293,0.640629,0.687503,1.148388,0.781252,0.693047,1.326661
11,1.316410,1.132817,1.132817,0.949219,1.155031,0.795412,0.713382,0.644535,0.607426,0.518560,...,0.533452,0.491216,0.679080,0.537114,0.544926,0.621098,1.036550,0.788535,0.562504,0.593754
32,0.755862,0.648441,0.716311,0.681888,0.503911,0.472662,0.543950,0.482793,0.495000,0.466314,...,0.218758,0.240242,0.697599,0.367194,0.396979,0.480286,0.739773,0.748971,0.607914,0.824465
60,0.673099,0.636112,0.602543,0.564213,0.539800,0.489324,0.454351,0.430670,0.429571,0.359320,...,0.241768,0.282966,0.297859,1.060734,1.140021,0.356574,0.434454,0.552922,1.233190,0.509404
88,0.613773,0.233406,0.548100,0.515752,0.484380,0.455572,0.468572,0.440008,0.386298,0.366583,...,0.222847,0.251350,0.195809,0.282356,0.211922,0.216805,0.232430,0.238289,0.251961,0.296882
179,0.420904,0.499395,0.473760,0.186165,0.431280,0.424963,0.404974,0.390265,0.362128,0.347480,...,0.221504,0.223244,0.210762,0.207405,0.204842,0.204842,0.205574,0.208260,0.209481,0.214852
298,0.469854,0.458502,0.439428,0.429144,0.409826,0.407263,0.384772,0.375647,0.352393,0.342994,...,0.214745,0.203560,0.375952,0.248054,0.294853,0.228157,0.627875,0.634421,0.244850,0.269325
396,0.468908,0.444067,0.421087,0.430334,0.408117,0.389441,0.378455,0.361899,0.350272,0.337882,...,0.210335,0.220268,0.213585,0.215248,0.239037,0.241386,0.225105,0.230965,0.235847,0.247841
578,0.436514,0.428900,0.414175,0.404364,0.381079,0.378699,0.367850,0.352958,0.345801,0.339087,...,0.242096,0.230225,0.217247,0.207421,0.257088,0.268013,0.264869,0.260261,0.263862,0.260780
760,0.425695,0.408011,0.391089,0.385474,0.371375,0.367789,0.353392,0.347403,0.337157,0.330771,...,0.245300,0.235222,0.238808,0.220200,0.227715,0.283226,0.242752,0.219719,0.282356,0.222382
942,0.392966,0.374869,0.381827,0.371451,0.361052,0.352958,0.346717,0.335380,0.332107,0.324149,...,0.246010,0.242836,0.242477,0.235741,0.232780,0.223976,0.222534,0.221993,0.218239,0.222618

In [112]:
na_count = mb_iv_std.isna().sum()
na_count

strike
120.0    0
125.0    0
130.0    0
135.0    0
140.0    0
145.0    0
150.0    0
155.0    0
160.0    0
165.0    0
170.0    0
175.0    0
180.0    0
185.0    0
190.0    0
195.0    0
200.0    0
205.0    0
210.0    0
dtype: int64

#### Preparing Interest Rate Data

In [7]:
print(mb_interest_rates)

   US_Treasury_Rates  Yield
0                 1m   5.62
1                 2m   5.27
2                 3m   5.29
3                 4m   5.46
4                 6m   5.36
5                 1y   5.02
6                 2y   4.28
7                 3y   3.98
8                 5y   3.76
9                 7y   3.74
10               10y   3.70
11               20y   4.07
12               30y   3.95

In [9]:
# function to convert tenor to number of days
def tenor_to_days(tenor):
    value = int(tenor[:-1])
    if 'm' in tenor:
        return value * 30  # approximate a month to 30 days
    elif 'y' in tenor:
        return value * 365  # approximate a year to 365 days

# create Tenor column and set as new index
mb_interest_rates['Tenor'] = mb_interest_rates['US_Treasury_Rates'].apply(tenor_to_days)
mb_interest_rates.set_index('Tenor', inplace=True)

# Renaming the Original Pillar Columns
mb_interest_rates.rename(columns={"US_Treasury_Rates": "Pillar"}, inplace=True)

print(mb_interest_rates)

      Pillar  Yield
Tenor
30        1m   5.62
60        2m   5.27
90        3m   5.29
120       4m   5.46
180       6m   5.36
365       1y   5.02
730       2y   4.28
1095      3y   3.98
1825      5y   3.76
2555      7y   3.74
3650     10y   3.70
7300     20y   4.07
10950    30y   3.95